title: Konstantinos-Marios Papakostas
author: Entry Java Developer
email: kostasmariospapakostas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is to share my Java projects. 
# social links
github_username: KostasMarios
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
